import { writable } from 'svelte/store'

export const darkmode = writable(false)
export const touchDevice = writable(false)
export const virtualKeyboardMode= writable(false)
export const toMarkup = writable((o) => o)
export const MathfieldElement = writable(null)
export const fontSize = writable(16)
export const magnify = writable(1)
export const formatLatex = writable((o) => o)
export const handleKeydown=writable(()=>{})
export const mathliveReady = writable(false)
export const mode = writable('')
export const correct_color = writable('')
export const incorrect_color = writable('')
export const unoptimal_color = writable('')